# Generated by Django 2.2.1 on 2019-05-19 13:05

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190519_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
    ]
